apiVersion: v1
kind: Secret
metadata:
  name: azure-key-vault-secrets
  namespace: example-namespace
data:
  SPD_KEY_VAULT_URI: aHR0cHM6Ly9rdi1hc3Nlc3NtZW50LWFwcC52YXVsdC5henVyZS5uZXQv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: your-docker-image
        ports:
        - containerPort: 8080
        env:
        - name: SPD_KEY_VAULT_URI
          valueFrom:
            secretKeyRef:
              name: azure-key-vault-secrets
              key: SPD_KEY_VAULT_URI
