apiVersion: v1
kind: Namespace
metadata:
  name: assessment-app


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-app
  namespace: assessment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment-app
  template:
    metadata:
      labels:
        app: assessment-app
    spec:
      containers:
      - name: assessment-app
        image: seu-registry/assessment-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPD_KEY_VAULT_URI
          value: "https://kv-assessment-app.vault.azure.net/"


---
apiVersion: v1
kind: Service
metadata:
  name: assessment-app-service
  namespace: assessment-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: assessment-app